spring:
  profiles:
    default: dev
    active: dev
  h2:
    console: enabled


productServiceAdapter:
  urlbase: http://localhost:8080/product

logging:
  level:
    root: warn
    core.ec: debug

